Diaries/Models/JudicialOfficer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel;

namespace Diaries.Models
{
    public class JudicialOfficer
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int JO_ID { get; set; }
        [StringLength(100)]
        [Display(Name = "Judicial Officer"), Required]
        public string JO_Name { get; set; }
        [StringLength(10)]
        [Display(Name = "Bacground Colour"), Required]
        public string JO_BackColor { get; set; }
        [StringLength(10)]
        [Display(Name = "Text Colour"), Required]
        public string JO_TextColor { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        [StringLength(100)]
        public string ModifiedBy { get; set; }
        public DateTime ModifiedOn { get; set; }
        [DefaultValue(false)]
        public bool Deleted { get; set; }

        public virtual ICollection<JudicialOfficerListing> VP_JOListings { get; set; }

    }
}

Diaries/Controllers/JudicialOfficerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Diaries.Models;
using System.DirectoryServices;
using System.Configuration;
using System.DirectoryServices.AccountManagement;

namespace Diaries.Controllers
{
    public class JudicialOfficerController : Controller
    {
        private DiariesDB db = new DiariesDB();

        // GET: judicialOfficer
        public async Task<ActionResult> Index()
        {
            // Check access levels and pass to view
            int index = User.Identity.Name.IndexOf("\\");
            string user = User.Identity.Name.Substring(index + 1);
            List<Access> AccessGroupsModel = db.tblAccess
                             .Where(r => r.UserId == user)
                             .ToList();

            var currentUser = (from u in db.tblAccess
                               where u.UserId == user
                               select u).FirstOrDefault();

            ViewData["InOwnerRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("owner")).Count() > 0 ? "true" : "false";
            ViewData["InSysAdminRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("system")).Count() > 0 ? "true" : "false";
            ViewData["InReadRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("read")).Count() > 0 ? "true" : "false";
            ViewData["InStandardRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("standard")).Count() > 0 ? "true" : "false";
            ViewData["InMagistratesReadRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("magistrate")).Count() > 0 ? "true" : "false";

            if ((ViewData["InSysAdminRole"] != "true") && (ViewData["InReadRole"] != "true") && (ViewData["InMagistratesReadRole"] != "true") && (ViewData["InStandardRole"] != "true") && (ViewData["InOwnerRole"] != "true"))
            {
                return RedirectToAction("Unauthorised", "Access");
            }

            if (currentUser != null)
                ViewData["UserName"] = currentUser.UserName;
            else
            { ViewData["UserName"] = User.Identity.Name; }

            return View(await db.tblJudicialOfficer.Where(d => d.Deleted == false).OrderBy(r => r.JO_Name).ToListAsync());
        }

        // GET: judicialOfficer/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JudicialOfficer judicialOfficer = await db.tblJudicialOfficer.FindAsync(id);
            if (judicialOfficer == null)
            {
                return HttpNotFound();
            }
            return View(judicialOfficer);
        }

        // GET: judicialOfficer/Create
        public ActionResult Create()
        {
            // Check access levels and pass to view
            int index = User.Identity.Name.IndexOf("\\");
            string user = User.Identity.Name.Substring(index + 1);
            List<Access> AccessGroupsModel = db.tblAccess
                             .Where(r => r.UserId == user)
                             .ToList();

            var currentUser = (from u in db.tblAccess
                               where u.UserId == user
                               select u).FirstOrDefault();

            ViewData["InOwnerRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("owner")).Count() > 0 ? "true" : "false";
            ViewData["InSysAdminRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("system")).Count() > 0 ? "true" : "false";
            ViewData["InReadRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("read")).Count() > 0 ? "true" : "false";
            ViewData["InStandardRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("standard")).Count() > 0 ? "true" : "false";
            ViewData["InMagistratesReadRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("magistrate")).Count() > 0 ? "true" : "false";

            if ((ViewData["InSysAdminRole"] != "true") && (ViewData["InReadRole"] != "true") && (ViewData["InMagistratesReadRole"] != "true") && (ViewData["InStandardRole"] != "true") && (ViewData["InOwnerRole"] != "true"))
            {
                return RedirectToAction("Unauthorised", "Access");
            }

            if (currentUser != null)
                ViewData["UserName"] = currentUser.UserName;
            else
            { ViewData["UserName"] = User.Identity.Name; }

            JudicialOfficer model = new JudicialOfficer();
            return View(model);
        }

        private bool IfJOExists(string joName)
        {
            bool returnValue = false;

            var recCount = db.tblJudicialOfficer
                .Where(r => r.JO_Name == joName && r.Deleted == false)
            .ToList();

            int totalRowsCount = recCount.Count();

            if (totalRowsCount == 0)
            {
                returnValue = true;
            }

            return returnValue;
        }

        // POST: judicialOfficer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "JO_ID,JO_Name,JO_BackColor,JO_TextColor")] JudicialOfficer judicialOfficer)
        {
            //Check for 
            if (ModelState.IsValid)
            {
                @ViewData["ErrorMessage"] = "";

                if (IfJOExists(judicialOfficer.JO_Name) == false)
                {
                    @ViewData["ErrorMessage"] = "Judicial Officer exists. Please re-check your entry.";
                    return View(judicialOfficer);
                }

                judicialOfficer.CreatedBy = User.Identity.Name;
                judicialOfficer.CreatedOn = DateTime.Now;
                judicialOfficer.ModifiedBy = User.Identity.Name;
                judicialOfficer.ModifiedOn = DateTime.Now;
                judicialOfficer.Deleted = false;
                db.tblJudicialOfficer.Add(judicialOfficer);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(judicialOfficer);
        }

        // GET: judicialOfficer/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            // Check access levels and pass to view
            int index = User.Identity.Name.IndexOf("\\");
            string user = User.Identity.Name.Substring(index + 1);
            List<Access> AccessGroupsModel = db.tblAccess
                             .Where(r => r.UserId == user)
                             .ToList();

            var currentUser = (from u in db.tblAccess
                               where u.UserId == user
                               select u).FirstOrDefault();

            ViewData["InOwnerRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("owner")).Count() > 0 ? "true" : "false";
            ViewData["InSysAdminRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("system")).Count() > 0 ? "true" : "false";
            ViewData["InReadRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("read")).Count() > 0 ? "true" : "false";
            ViewData["InStandardRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("standard")).Count() > 0 ? "true" : "false";
            ViewData["InMagistratesReadRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("magistrate")).Count() > 0 ? "true" : "false";

            if ((ViewData["InSysAdminRole"] != "true") && (ViewData["InReadRole"] != "true") && (ViewData["InMagistratesReadRole"] != "true") && (ViewData["InStandardRole"] != "true") && (ViewData["InOwnerRole"] != "true"))
            {
                return RedirectToAction("Unauthorised", "Access");
            }

            if (currentUser != null)
                ViewData["UserName"] = currentUser.UserName;
            else
            { ViewData["UserName"] = User.Identity.Name; }

            if (id == null)
            {
                return RedirectToAction("Alert", "Access", new { alertMessage = "Judicial Officer not found, please contact administrator." });
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JudicialOfficer judicialOfficer = await db.tblJudicialOfficer.FindAsync(id);
            if (judicialOfficer == null)
            {
                return RedirectToAction("Alert", "Access", new { alertMessage = "Judicial Officer not found, please contact administrator." });
            }
            return View(judicialOfficer);
        }

        // POST: judicialOfficer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "JO_ID,JO_Name,JO_BackColor,JO_TextColor,CreatedBy, CreatedOn")] JudicialOfficer judicialOfficer)
        {
            if (ModelState.IsValid)
            {
                judicialOfficer.ModifiedBy = User.Identity.Name;
                judicialOfficer.ModifiedOn = DateTime.Now;
                judicialOfficer.Deleted = false;

Diaries/Views/JudicialOfficer/Create.cshtml
@model Diaries.Models.JudicialOfficer

@{
    ViewBag.Title = "Create Judicial Officer";
}

<h3>Judicial Officer</h3>
<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.JO_ID)

    <table border="0">
        <tr>
            <td class="auto-style16">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "Index", "JudicialOfficer", new { @class = "btn btn-danger" })
            </td>
        </tr>
    </table>


    <table border="1" cellspacing="0" cellpadding="10">
        <tr>
            <td>
                <table border="0" style="font-family: Arial; float: left; font-size: 9pt; background-color: whitesmoke; width: auto; height: 100%; ">
                    <tr style="background-color: #46568c; color: white; "><th align="center"><b>Part Heard Judicial Office Details</b></th></tr>
                    <tr>
                        <td class="auto-style12">
                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: whitesmoke; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Judicial Officer:
                                    </td>
                                    <td align="left">
                                        <input id="JudicialOfficersDataList" type="text" name="JO_Name" list="JO_Name" value=@Html.Raw('"')@Model.JO_Name@Html.Raw('"') style="width:100%" />
                                        <datalist data-autocompleteme='@Url.Action("getUsers")' data-val="true" data-val-length="Please enter the user." data-val-length-max="500" id="JO_Name"></datalist>
                                        @Html.ValidationMessageFor(model => model.JO_Name)
                                    </td>
                                </tr>

                            </table>

                        </td>

                    </tr>

                </table>



                <table border="0" style="font-family: Arial; float: right; font-size: 9pt; background-color: whitesmoke; width: auto; height: 100%; ">
                    <tr style="background-color: #46568c; color: white; "><th align="center"><b>Part Heard Judicial Office Colours</b></th></tr>
                    <tr>
                        <td class="auto-style12">
                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: whitesmoke; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Background Colour:
                                    </td>
                                    <td align="left" class="input-group color">
                                        <span class="input-group-addon"><i></i></span>

                                        @Html.ColorPickAreaFor(Model.JO_BackColor,Model.JO_BackColor, "JO_BackColor")                                       
                                        @Html.ValidationMessageFor(model => model.JO_BackColor)
                                        
                                        @*<input type="text" name=model. value="" class="form-control" />*@
                                    </td>
                                </tr>

                            </table>
                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: whitesmoke; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Text Colour:
                                    </td>
                                    <td align="left" class="input-group color">
                                        <span class="input-group-addon"><i></i></span>
                                        @Html.ColorPickAreaFor(Model.JO_TextColor, Model.JO_TextColor, "JO_TextColor")
                                        @Html.ValidationMessageFor(model => model.JO_TextColor)
                                    </td>
                                </tr>

                            </table>                        
                        </td>
                    </tr>
                </table>

            </td>
        </tr>
    </table>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}



Diaries/Views/JudicialOfficer/Details.cshtml
@model Diaries.Models.JudicialOfficer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>judicialOfficer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.JO_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JO_Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.JO_ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Diaries/Views/JudicialOfficer/Edit.cshtml
@model Diaries.Models.JudicialOfficer

@{
    ViewBag.Title = "Edit Judicial Officer";
}

<h3>Judicial Officer</h3>
<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.JO_ID)
    @Html.HiddenFor(model => model.CreatedBy)
    @Html.HiddenFor(model => model.CreatedOn)
    @Html.HiddenFor(model => model.ModifiedBy)
    @Html.HiddenFor(model => model.ModifiedBy)

    <table border="0">
        <tr>
            <td class="auto-style16">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "Index", "JudicialOfficer", new { @class = "btn btn-danger" })
            </td>
        </tr>
    </table>

    <br />

    <table border="1" cellspacing="0" cellpadding="10">
        <tr>
            <td>
                <table border="0" style="font-family: Arial; float: left; font-size: 9pt; background-color: whitesmoke; width: auto; height: 100%; ">
                    <tr style="background-color: #46568c; color: white; "><th align="center"><b>Part Heard Judicial Office Details</b></th></tr>
                    <tr>
                        <td class="auto-style12">
                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: whitesmoke; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Judicial Officer:
                                    </td>
                                    <td align="left">
                                        <input id="JudicialOfficersDataList" type="text" name="JO_Name" list="JO_Name" value=@Html.Raw('"')@Model.JO_Name@Html.Raw('"') style="width:100%" />
                                        <datalist data-autocompleteme='@Url.Action("getUsers")' data-val="true" data-val-length="Please enter the user." data-val-length-max="500" id="JO_Name"></datalist>
                                        @Html.ValidationMessageFor(model => model.JO_Name)
                                    </td>
                                </tr>

                            </table>

                        </td>

                    </tr>

                </table>



                <table border="0" style="font-family: Arial; float: right; font-size: 9pt; background-color: whitesmoke; width: auto; height: 100%; ">
                    <tr style="background-color: #46568c; color: white; "><th align="center"><b>Part Heard Judicial Office Colours</b></th></tr>
                    <tr>
                        <td class="auto-style12">
                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: whitesmoke; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Background Colour:
                                    </td>
                                    <td align="left" class="input-group color">
                                        <span class="input-group-addon"><i></i></span>

                                        @Html.ColorPickAreaFor(Model.JO_BackColor, Model.JO_BackColor, "JO_BackColor")
                                        @Html.ValidationMessageFor(model => model.JO_BackColor)

                                        @*<input type="text" name=model. value="" class="form-control" />*@
                                    </td>
                                </tr>

                            </table>
                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: whitesmoke; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Text Colour:
                                    </td>
                                    <td align="left" class="input-group color">
                                        <span class="input-group-addon"><i></i></span>
                                        @Html.ColorPickAreaFor(Model.JO_TextColor, Model.JO_TextColor, "JO_TextColor")
                                        @Html.ValidationMessageFor(model => model.JO_TextColor)
                                    </td>
                                </tr>

                            </table>
                        </td>
                    </tr>
                </table>

            </td>
        </tr>
    </table>
}

<div>
    @section DocumentLog
{
        <table border="1" cellspacing="0" cellpadding="4" style="font-family: Arial; font-size: 10pt; width: 100%; background-color: threedlightshadow;">
            <tr>
                <td align="left" nowrap class="auto-style14">
                    Record modified by @Model.ModifiedBy on @Model.ModifiedOn.ToString("dd-MM-yyyy")
                </td>
            </tr>
        </table>

        <table border="1" cellspacing="0" cellpadding="4" style="font-family: Arial; font-size: 10pt; width: 100%; background-color: threedlightshadow;">
            <tr>
                <td align="left" nowrap class="auto-style14">
                    Record created by @Model.CreatedBy on @Model.CreatedOn.ToString("dd-MM-yyyy")
                </td>
            </tr>
        </table>
    }

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


    

Diaries/Views/JudicialOfficer/Index.cshtml
@model IEnumerable<Diaries.Models.JudicialOfficer>

@{
    ViewBag.Title = "Judicial Officers";
}

<h3>Judicial Officers</h3>
<br />
<p>
    @Html.ActionLink("Add", "Create", null, new { @class = "btn btn-primary" })
</p>


@*<table border="1" style="font-family: Arial; float: left; font-size: 9pt; background-color: whitesmoke; width: auto; height: 100%; ">
    <tr style="background-color: #46568c; color: white; "><th align="center"><b>Judicial Officers</b></th></tr>
    <tr>
        <td class="auto-style12">

            <div style="overflow:auto; height:120px; width:720px; font-family: arial; float: left; font-size: 9pt; background-color: whitesmoke;">

                <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: white; float: left" cellspacing="0" cellpadding="0">

                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr style="background-color: threedlightshadow;">
                                <td>
                                    @Html.DisplayFor(modelItem => item.JO_Name)
                                    &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                                    @Html.ActionLink("Edit", "Edit", "JudicialOfficer", new { id = item.JO_ID }, null)
                                    &nbsp; &nbsp; &nbsp;
                                    @Html.ActionLink("Delete", "Delete", "JudicialOfficer", new { id = item.JO_ID },null)

                                    @Html.ActionLink("Edit", "Edit", "JudicialOfficer", new { id = item.JO_ID, @class = "btn btn-primary" })
                                    @Html.ActionLink("Delete", "Delete", "JudicialOfficer", new { id = item.JO_ID, @class = "btn btn-primary" })
                                </td>
                            </tr>

                        }
                    }

                </table>
            </div>
        </td>
    </tr>
</table>*@


<table border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td>
            <div style="overflow:auto; height:100px; width:100%; font-family: arial; float: left; font-size: 9pt; background-color: whitesmoke;">
                <table border="1" style="font-family: Arial; float: left; font-size: 9pt; background-color: whitesmoke; width: auto; height: 100%; ">
                    <tr style="background-color: #46568c; color: white; "><th align="center"><b>Judicial Officers</b></th></tr>
                    <tr>
                        <td class="auto-style12">
                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: whitesmoke; float: left" cellspacing="0" cellpadding="0">
                                <thead>
                                    <tr>
                                        @*<th>@Html.DisplayNameFor(model => model.JO_Name)</th>
                                        <td>&nbsp</td>*@
                                    </tr>
                                </thead>

                                <tbody>
                                    @if (Model != null)
                                    {
                                        int i = 0;
                                        foreach (var item in Model)
                                        {
                                                i = i + 1;
                                                <tr style="background-color: @(i % 2 == 0 ? "threedlightshadow": "whitesmoke");">

                                                <td>@Html.DisplayFor(modelItem => item.JO_Name) </td>
                                                <td>@Html.ActionLink("Edit", "Edit", "JudicialOfficer", new { id = item.JO_ID, @class = "btn btn-primary", @style = "width:100px" }, null) &nbsp;&nbsp;&nbsp; @Html.ActionLink("Delete", "Delete", "JudicialOfficer", new { id = item.JO_ID, @class = "btn btn-primary", @style = "width:100px" }, null) &nbsp;&nbsp;&nbsp; @Html.ActionLink("Listing Rules", "Index", "JudicialOfficerListing", new { joid = item.JO_ID, @class = "btn btn-primary", @style = "width:100px" }, null)</td>

                                            </tr>
                                        }
                                    }

                                </tbody>
                            </table>

                        </td>

                    </tr>

                </table>
            </div>
        </td>
    </tr>
</table>

@*<table id="judicialofficers" border="0" cellpadding="10" cellspacing="0">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.JO_Name)</th>
            <td>&nbsp</td>
        </tr>
    </thead>

    <tbody>
        @if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr>

                    <td>@Html.DisplayFor(modelItem => item.JO_Name) </td>
                    <td>@Html.ActionLink("Edit", "Edit", "JudicialOfficer", new { id = item.JO_ID, @class = "btn btn-primary", @style = "width:100px" },null) &nbsp;&nbsp;&nbsp; @Html.ActionLink("Delete", "Delete", "JudicialOfficer", new { id = item.JO_ID, @class = "btn btn-primary", @style = "width:100px" } ,null) &nbsp;&nbsp;&nbsp; @Html.ActionLink("Listing Rules", "Index", "JudicialOfficerListing", new { joid = item.JO_ID, @class = "btn btn-primary", @style = "width:100px" }, null)</td>

                </tr>
            }
        }
    </tbody>
</table>*@