Diaries/Models/VacateReason.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel;

namespace Diaries.Models
{
    public class VacateReason
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int VR_ID { get; set; }
        [StringLength(30)]
        [Display(Name = "Vacate Reason"), Required]
        public string VR_Name { get; set; }
        [StringLength(30)]
        [Display(Name = "Vacate Reason Type"), Required]
        public string VR_Type { get; set; }
        [StringLength(100)]
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        [StringLength(100)]
        public string ModifiedBy { get; set; }
        public DateTime ModifiedOn { get; set; }
        [DefaultValue(false)]
        public bool Deleted { get; set; }
    }
}

Diaries/Controllers/VacateReasonController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Diaries.Models;

namespace Diaries.Controllers
{
    public class VacateReasonController : Controller
    {
        private DiariesDB db = new DiariesDB();

        // GET: /CaseOutcome/
        public ActionResult Index()
        {
            // Check access levels and pass to view
            int index = User.Identity.Name.IndexOf("\\");
            string user = User.Identity.Name.Substring(index + 1);
            List<Access> AccessGroupsModel = db.tblAccess
                             .Where(r => r.UserId == user)
                             .ToList();

            var currentUser = (from u in db.tblAccess
                               where u.UserId == user
                               select u).FirstOrDefault();

            ViewData["InOwnerRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("owner")).Count() > 0 ? "true" : "false";
            ViewData["InSysAdminRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("system")).Count() > 0 ? "true" : "false";
            ViewData["InReadRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("read")).Count() > 0 ? "true" : "false";
            ViewData["InStandardRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("standard")).Count() > 0 ? "true" : "false";
            ViewData["InMagistratesReadRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("magistrate")).Count() > 0 ? "true" : "false";

            if ((ViewData["InSysAdminRole"] != "true") && (ViewData["InReadRole"] != "true") && (ViewData["InMagistratesReadRole"] != "true") && (ViewData["InStandardRole"] != "true") && (ViewData["InOwnerRole"] != "true"))
            {
                return RedirectToAction("Unauthorised", "Access");
            }

            if (currentUser != null)
                ViewData["UserName"] = currentUser.UserName;
            else
            { ViewData["UserName"] = User.Identity.Name; }

            var model = db.tblVacateReason
                .Where(r => r.Deleted == false)
            .ToList();

            var modelsorted = model.OrderBy(r => r.VR_Type).ThenBy(e => e.VR_Name).ToList();

            return View(modelsorted);
        }

        // GET: /CaseOutcome/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VacateReason VacateReason = await db.tblVacateReason.FindAsync(id);
            if (VacateReason == null)
            {
                return HttpNotFound();
            }
            return View(VacateReason);
        }

        // GET: /CaseOutcome/Create
        public ActionResult Create()
        {
            // Check access levels and pass to view
            int index = User.Identity.Name.IndexOf("\\");
            string user = User.Identity.Name.Substring(index + 1);
            List<Access> AccessGroupsModel = db.tblAccess
                             .Where(r => r.UserId == user)
                             .ToList();

            var currentUser = (from u in db.tblAccess
                               where u.UserId == user
                               select u).FirstOrDefault();

            ViewData["InOwnerRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("owner")).Count() > 0 ? "true" : "false";
            ViewData["InSysAdminRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("system")).Count() > 0 ? "true" : "false";
            ViewData["InReadRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("read")).Count() > 0 ? "true" : "false";
            ViewData["InStandardRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("standard")).Count() > 0 ? "true" : "false";
            ViewData["InMagistratesReadRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("magistrate")).Count() > 0 ? "true" : "false";

            if ((ViewData["InSysAdminRole"] != "true") && (ViewData["InReadRole"] != "true") && (ViewData["InMagistratesReadRole"] != "true") && (ViewData["InStandardRole"] != "true") && (ViewData["InOwnerRole"] != "true"))
            {
                return RedirectToAction("Unauthorised", "Access");
            }

            if (currentUser != null)
                ViewData["UserName"] = currentUser.UserName;
            else
            { ViewData["UserName"] = User.Identity.Name; }

            VacateReason model = new VacateReason();

            var vrTypeModel = getTypes();
            SelectList VRTypes = new SelectList(vrTypeModel);
            ViewData["VRTypes"] = VRTypes;

            // pass the view model to the view
            return View(model);
        }

        // POST: /CaseOutcome/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "VR_ID,VR_Name,VR_Type,CreatedBy,CreatedOn,ModifiedBy,ModifiedOn,Deleted")] VacateReason vacatereason)
        {
            if (ModelState.IsValid)
            {

                @ViewData["ErrorMessage"] = "";

                if (IsDuplicate(vacatereason, "Add") == false)
                {
                    @ViewData["ErrorMessage"] = "Vacate Reason exists. Please re-check your entry.";
                    var vrTypeModel = getTypes();
                    SelectList VRTypes = new SelectList(vrTypeModel);
                    ViewData["VRTypes"] = VRTypes;
                    return View(vacatereason);
                }

                vacatereason.CreatedBy = User.Identity.Name;
                vacatereason.CreatedOn = DateTime.Now;
                vacatereason.ModifiedBy = User.Identity.Name;
                vacatereason.ModifiedOn = DateTime.Now;
                vacatereason.Deleted = false;

                db.tblVacateReason.Add(vacatereason);
                await db.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View(vacatereason);
        }

        // GET: /CaseOutcome/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            // Check access levels and pass to view
            int index = User.Identity.Name.IndexOf("\\");
            string user = User.Identity.Name.Substring(index + 1);
            List<Access> AccessGroupsModel = db.tblAccess
                             .Where(r => r.UserId == user)
                             .ToList();

            var currentUser = (from u in db.tblAccess
                               where u.UserId == user
                               select u).FirstOrDefault();

            ViewData["InOwnerRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("owner")).Count() > 0 ? "true" : "false";
            ViewData["InSysAdminRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("system")).Count() > 0 ? "true" : "false";
            ViewData["InReadRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("read")).Count() > 0 ? "true" : "false";
            ViewData["InStandardRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("standard")).Count() > 0 ? "true" : "false";
            ViewData["InMagistratesReadRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("magistrate")).Count() > 0 ? "true" : "false";

            if ((ViewData["InSysAdminRole"] != "true") && (ViewData["InReadRole"] != "true") && (ViewData["InMagistratesReadRole"] != "true") && (ViewData["InStandardRole"] != "true") && (ViewData["InOwnerRole"] != "true"))
            {
                return RedirectToAction("Unauthorised", "Access");
            }

            if (currentUser != null)
                ViewData["UserName"] = currentUser.UserName;
            else
            { ViewData["UserName"] = User.Identity.Name; }

            if (id == null)
            {
                return RedirectToAction("Alert", "Access", new { alertMessage = "Vacate Reason not found, please contact administrator." });
            }
            VacateReason vacatereason = await db.tblVacateReason.FindAsync(id);
            if (vacatereason == null)
            {
                return RedirectToAction("Alert", "Access", new { alertMessage = "Vacate Reason not found, please contact administrator." });
            }

            var selectedItem = db.tblVacateReason.Where(r => r.VR_ID == id).Single();
            SelectList VRTypes = new SelectList(getTypes(), selectedItem.ToString());
            ViewData["VRTypes"] = VRTypes;

            // pass the view model to the view
            return View(vacatereason);
        }

        // POST: /CaseOutcome/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "VR_ID,VR_Name,VR_Type,CreatedBy,CreatedOn,ModifiedBy,ModifiedOn,Deleted")] VacateReason vacatereason)
        {
            if (ModelState.IsValid)
            {
                @ViewData["ErrorMessage"] = "";

                if (IsDuplicate(vacatereason, "Edit") == false)
                {

Diaries/Views/VacateReason/Create.cshtml
@model Diaries.Models.VacateReason

@{
    ViewBag.Title = "Create Vacate Reason";
}

<h3>Create Vacate Reason</h3>
<p></p>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.VR_ID)

    <p style="font-size:inherit;color:red">@ViewData["ErrorMessage"]</p>

    <table border="0">
        <tr>
            <td class="auto-style16">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "Index", "VacateReason", new { @class = "btn btn-danger" })
            </td>
        </tr>
    </table>
    <br />


    <table border="1" cellspacing="0" cellpadding="10">
        <tr>
            <td>
                <table border="0" style="font-family: Arial; float: left; font-size: 9pt; background-color: whitesmoke; width: auto; height: 100%; ">
                    <tr style="background-color: #46568c; color: white; "><th align="center"><b>Vacate Reason Details</b></th></tr>
                    <tr>
                        <td class="auto-style12">
                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: whitesmoke; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Vacate Reason:
                                    </td>
                                    <td align="left">
                                        @Html.EditorFor(model => model.VR_Name)
                                        @Html.ValidationMessageFor(model => model.VR_Name)
                                    </td>
                                </tr>

                            </table>

                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: whitesmoke; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Vacate Reason Type:
                                    </td>
                                    <td align="left">
                                        @Html.DropDownList("VR_Type", ViewData["VRTypes"] as SelectList)
                                        @Html.ValidationMessageFor(model => model.VR_Type)
                                    </td>
                                </tr>

                            </table>

                        </td>

                    </tr>

                </table>

            </td>
        </tr>
    </table>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}



Diaries/Views/VacateReason/Delete.cshtml
@model Diaries.Models.VacateReason

@{
    ViewBag.Title = "Create Vacate Reason";
}

<h3>Delete Vacate Reason</h3>

<h4>Please confirm delete?</h4>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.VR_ID)

    <p style="font-size:inherit;color:red">@ViewData["ErrorMessage"]</p>

    <table border="0">
        <tr>
            <td class="auto-style16">
                <input type="submit" value="Delete" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "Index", "VacateReason", new { @class = "btn btn-danger" })
            </td>
        </tr>
    </table>
    <br />


    <table border="1" cellspacing="0" cellpadding="10">
        <tr>
            <td>
                <table border="0" style="font-family: Arial; float: left; font-size: 9pt; background-color: whitesmoke; width: auto; height: 100%; ">
                    <tr style="background-color: #46568c; color: white; "><th align="center"><b>Vacate Reason Details</b></th></tr>
                    <tr>
                        <td class="auto-style12">
                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: whitesmoke; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Vacate Reason:
                                    </td>
                                    <td align="left">
                                        @Html.DisplayFor(model => model.VR_Name)
                                        @Html.ValidationMessageFor(model => model.VR_Name)
                                    </td>
                                </tr>

                            </table>

                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: whitesmoke; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Vacate Reason Type:
                                    </td>
                                    <td align="left">
                                        @Html.DisplayFor(model => model.VR_Type)
                                        @Html.ValidationMessageFor(model => model.VR_Type)
                                    </td>
                                </tr>

                            </table>

                        </td>

                    </tr>

                </table>

            </td>
        </tr>
    </table>
}

<div>
    @section DocumentLog
{
        <table border="1" cellspacing="0" cellpadding="4" style="font-family: Arial; font-size: 10pt; width: 100%; background-color: threedlightshadow;">
            <tr>
                <td align="left" nowrap class="auto-style14">
                    Record modified by @Model.CreatedBy on @Model.CreatedOn.ToString("dd-MM-yyyy")
                </td>
            </tr>
        </table>

        <table border="1" cellspacing="0" cellpadding="4" style="font-family: Arial; font-size: 10pt; width: 100%; background-color: threedlightshadow;">
            <tr>
                <td align="left" nowrap class="auto-style14">
                    Record created by @Model.ModifiedBy on @Model.ModifiedOn.ToString("dd-MM-yyyy")
                </td>
            </tr>
        </table>
    }

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}



Diaries/Views/VacateReason/Details.cshtml
@model Diaries.Models.VacateReason

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>VacateReason</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.VR_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VR_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VR_Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VR_Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedOn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Deleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deleted)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.VR_ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Diaries/Views/VacateReason/Edit.cshtml
@model Diaries.Models.VacateReason

@{
    ViewBag.Title = "Edit Vacate Reason";
}

<h3>Edit Vacate Reason</h3>
<p></p>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.VR_ID)
    @Html.HiddenFor(model => model.CreatedBy)
    @Html.HiddenFor(model => model.CreatedOn)
    
    <p style="font-size:inherit;color:red">@ViewData["ErrorMessage"]</p>

    <table border="0">
        <tr>
            <td class="auto-style16">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "Index", "VacateReason", new { @class = "btn btn-danger" })
            </td>
        </tr>
    </table>
    <br />


    <table border="1" cellspacing="0" cellpadding="10">
        <tr>
            <td>
                <table border="0" style="font-family: Arial; float: left; font-size: 9pt; background-color: whitesmoke; width: auto; height: 100%; ">
                    <tr style="background-color: #46568c; color: white; "><th align="center"><b>Vacate Reason Details</b></th></tr>
                    <tr>
                        <td class="auto-style12">
                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: whitesmoke; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Vacate Reason:
                                    </td>
                                    <td align="left">
                                        @Html.EditorFor(model => model.VR_Name)
                                        @Html.ValidationMessageFor(model => model.VR_Name)
                                    </td>
                                </tr>

                            </table>

                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: whitesmoke; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Vacate Reason Type:
                                    </td>
                                    <td align="left">
                                        @Html.DropDownList("VR_Type", ViewData["VRTypes"] as SelectList)
                                        @Html.ValidationMessageFor(model => model.VR_Type)
                                    </td>
                                </tr>

                            </table>

                        </td>

                    </tr>

                </table>

            </td>
        </tr>
    </table>
}

<div>
    @section DocumentLog
{
        <table border="1" cellspacing="0" cellpadding="4" style="font-family: Arial; font-size: 10pt; width: 100%; background-color: threedlightshadow;">
            <tr>
                <td align="left" nowrap class="auto-style14">
                    Record modified by @Model.CreatedBy on @Model.CreatedOn.ToString("dd-MM-yyyy")
                </td>
            </tr>
        </table>

        <table border="1" cellspacing="0" cellpadding="4" style="font-family: Arial; font-size: 10pt; width: 100%; background-color: threedlightshadow;">
            <tr>
                <td align="left" nowrap class="auto-style14">
                    Record created by @Model.ModifiedBy on @Model.ModifiedOn.ToString("dd-MM-yyyy")
                </td>
            </tr>
        </table>
    }

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}



Diaries/Views/VacateReason/Index.cshtml
@model IEnumerable<Diaries.Models.VacateReason>

@{
    ViewBag.Title = "Vacate Reasons";
}

<h3>Vacate Reasons</h3>
@*<br />*@
<p>
    @Html.ActionLink("Add", "Create", null, new { @class = "btn btn-primary" })
</p>

<table border="1" cellspacing="0" cellpadding="10" style="width: auto; height: 100%">
    <tr>
        <td>
            <table border="0" style="font-family: Arial; float: left; font-size: 9pt; background-color: whitesmoke; width: 950px; height: 100%; ">
                @*<tr style="background-color: #46568c; color: white; "><th align="center"><b>Access Group Listings</b></th></tr>*@
                <tr>
                    <td>
                        <table id="caseoutcomes" border="0" cellpadding="0" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>@Html.DisplayNameFor(model => model.VR_Type)</th>
                                    <th>@Html.DisplayNameFor(model => model.VR_Name)</th>
                                    <td>&nbsp</td>
                                    <td>&nbsp</td>
                                </tr>
                            </thead>

                            <tbody>
                                @if (Model != null)
                                {
                                    foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@Html.DisplayFor(modelItem => item.VR_Type)</td>
                                            <td id="tab1"> @Html.DisplayFor(modelItem => item.VR_Name)</td>
                                            <td>@Html.ActionLink("Edit", "Edit", "VacateReason", new { id = item.VR_ID }, null)</td>
                                            <td>@Html.ActionLink("Delete", "Delete", "VacateReason", new { id = item.VR_ID }, null)</td>

                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>