Diaries/Models/DayNote.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel;
using System.Web.Mvc;

namespace Diaries.Models
{
    public class DayNote
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int DN_ID { get; set; }
        [Display(Name = "Start Date"), Required]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public DateTime DN_Start_Date { get; set; }
        [Display(Name = "End Date"), Required]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public DateTime DN_End_Date { get; set; }
        
        [StringLength(10)]
        [Display(Name = "Background Colour"), Required]
        public string DN_BackColor { get; set; }
        [StringLength(10)]
        [Display(Name = "Text Colour"), Required]
        public string DN_TextColor { get; set; }
        [StringLength(100)]
        [Display(Name = "Notes"), Required]
        public string DN_Note { get; set; }
        //[DefaultValue(true)]
        //[Display(Name = "Apply To"), Required]
        //public bool DN_All_Diaries { get; set; }
        //public IEnumerable<DN_Diaries> Features { get; set; }
        [DefaultValue(true)]
        public bool IsActive { get; set; }
        [StringLength(100)]
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        [StringLength(100)]
        public string ModifiedBy { get; set; }
        public DateTime ModifiedOn { get; set; }
        [DefaultValue(false)]
        public bool Deleted { get; set; }

        //this list has all movies available for dropdown
        public List<D_Diaries> AvailableDiaries { get; set; }
        //this list has our default values 
        public List<D_Diaries> DefaultDiaries { get; set; }
        //this will retrieve the ids of movies selected in list when submitted
        [Display(Name = "Submitted Diaries")]
        public List<string> SubmittedDiaries { get; set; }

        public List<DN_ApplyToList> EditableDiaries { get; set; }
        //this list has our default values 
        public List<DN_ApplyToList> DefaultEditableDiaries { get; set; }

        //public virtual IEnumerable<int> DN_SelectedApplyToListCollection { get; set; }
        //public virtual IEnumerable<SelectListItem> DN_ApplyToListCollection { get; set; }

        public virtual ICollection<DN_ApplyToList> DN_DiaryListCollection { get; set; }
    }
}

Diaries/Controllers/DayNoteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Diaries.Models;

namespace Diaries.Controllers
{
    public class DayNoteController : Controller
    {
        private DiariesDB db = new DiariesDB();

        // GET: DayNote
        public class JQueryDataTableParamModel
        {
            public string sEcho { get; set; }
            public string sSearch { get; set; }
            public int iDisplayLength { get; set; }
            public int iDisplayStart { get; set; }
            public string first_data { get; set; }
            public string second_data { get; set; }
        }

        public JsonResult GetAjaxData(JQueryDataTableParamModel param)
        {

            var model = db.tblDayNote
               .Where(r => r.Deleted == false)
               .Select(r => new DayNoteVM { VM_Active = r.IsActive ? "Active" : "Inactive", VM_Year = r.DN_Start_Date.Year , VM_Start = r.DN_Start_Date, VM_End = r.DN_End_Date, VM_Note = r.DN_Note, VM_Id = r.DN_ID})
                .ToList();

            List<DayNoteVM> modelsorted;

            int totalRowsCount = 0;
            int filteredRowsCount = 0;
            string[][] aaData;

            if (param.first_data != null && param.second_data != null)
            {
                List<DayNoteVM> aa = new List<DayNoteVM>();
                foreach (var group in model)
                {
                    var test = group.VM_Active.Replace(" ", "").Trim('-').ToLower();
                    var test1 = group.VM_Year;
                    if (test.Contains(param.first_data) &&
                        test1.ToString().Contains(param.second_data))
                        aa.Add(group);
                }

                modelsorted = aa.OrderBy(r => r.VM_Active).ThenBy(e => e.VM_Year).ToList();
                aa = null;

                aaData = modelsorted.Select(d => new string[] { d.VM_Active, d.VM_Year.ToString(), d.VM_Start.ToString("dd-MM-yyyy"), d.VM_End.ToString("dd-MM-yyyy"), d.VM_Note, d.VM_Id.ToString() }).ToArray();

                totalRowsCount = modelsorted.Count();
                filteredRowsCount = modelsorted.Count();

                return Json(new
                {
                    sEcho = param.sEcho,
                    aaData = aaData,
                    iTotalRecords = Convert.ToInt32(totalRowsCount),
                    iTotalDisplayRecords = Convert.ToInt32(filteredRowsCount)
                }, JsonRequestBehavior.AllowGet);


            }

            if (param.sSearch != null)
            {
                if (param.sSearch.Length > 2)
                {

                    List<DayNoteVM> aa = new List<DayNoteVM>();
                    foreach (var group in model)
                    {
                        if (group.VM_Active.ToLower().Contains(param.sSearch.ToLower()) || group.VM_Year.ToString().Contains(param.sSearch.ToLower()) || group.VM_Note.ToLower().Contains(param.sSearch.ToLower()) || group.VM_End.ToString("dd-MM-yyyy").ToLower().Contains(param.sSearch.ToLower()) ||
                            group.VM_Start.ToString("dd-MM-yyyy").ToLower().Contains(param.sSearch.ToLower()))

                            aa.Add(group);

                    }

                    modelsorted = aa.OrderBy(r => r.VM_Active).ThenBy(e => e.VM_Year).ToList();
                    aa = null;
                    aaData = modelsorted.Select(d => new string[] { d.VM_Active, d.VM_Year.ToString(), d.VM_Start.ToString("dd-MM-yyyy"), d.VM_End.ToString("dd-MM-yyyy"), d.VM_Note, d.VM_Id.ToString() }).ToArray();

                    totalRowsCount = modelsorted.Count();
                    filteredRowsCount = modelsorted.Count();

                    return Json(new
                    {
                        sEcho = param.sEcho,
                        aaData = aaData,
                        iTotalRecords = Convert.ToInt32(totalRowsCount),
                        iTotalDisplayRecords = Convert.ToInt32(filteredRowsCount)
                    }, JsonRequestBehavior.AllowGet);
                }

            }

            totalRowsCount = model.Count();
            filteredRowsCount = model.Count();
            var vv = model.Select(r => new { r.VM_Active, r.VM_Year }).Distinct().OrderBy(r => r.VM_Active).ThenBy(e => e.VM_Year).ToList();

            aaData = vv.Select(d => new string[] { d.VM_Active, d.VM_Year.ToString(), "", "", "", "", "", "" }).ToArray();


            return Json(new
            {
                sEcho = param.sEcho,
                aaData = aaData,
                iTotalRecords = Convert.ToInt32(totalRowsCount),
                iTotalDisplayRecords = Convert.ToInt32(filteredRowsCount)
            }, JsonRequestBehavior.AllowGet);

        }
        public async Task<ActionResult> Index()
        {
            // Check access levels and pass to view
            int index = User.Identity.Name.IndexOf("\\");
            string user = User.Identity.Name.Substring(index + 1);
            List<Access> AccessGroupsModel = db.tblAccess
                             .Where(r => r.UserId == user)
                             .ToList();

            var currentUser = (from u in db.tblAccess
                               where u.UserId == user
                               select u).FirstOrDefault();

            ViewData["InOwnerRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("owner")).Count() > 0 ? "true" : "false";
            ViewData["InSysAdminRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("system")).Count() > 0 ? "true" : "false";
            ViewData["InReadRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("read")).Count() > 0 ? "true" : "false";
            ViewData["InStandardRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("standard")).Count() > 0 ? "true" : "false";
            ViewData["InMagistratesReadRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("magistrate")).Count() > 0 ? "true" : "false";

            if ((ViewData["InSysAdminRole"] != "true") && (ViewData["InReadRole"] != "true") && (ViewData["InMagistratesReadRole"] != "true") && (ViewData["InStandardRole"] != "true") && (ViewData["InOwnerRole"] != "true"))
            {
                return RedirectToAction("Unauthorised", "Access");
            }

            if (currentUser != null)
                ViewData["UserName"] = currentUser.UserName;
            else
            { ViewData["UserName"] = User.Identity.Name; }

            return View(await db.tblDayNote.ToListAsync());
        }

        // GET: DayNote/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DayNote dayNote = await db.tblDayNote.FindAsync(id);
            if (dayNote == null)
            {
                return HttpNotFound();
            }
            return View(dayNote);
        }

        // GET: DayNote/Create
        public ActionResult Create()
        {

            // Check access levels and pass to view
            int index = User.Identity.Name.IndexOf("\\");
            string user = User.Identity.Name.Substring(index + 1);
            List<Access> AccessGroupsModel = db.tblAccess
                             .Where(r => r.UserId == user)
                             .ToList();

            var currentUser = (from u in db.tblAccess
                               where u.UserId == user
                               select u).FirstOrDefault();

            ViewData["InOwnerRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("owner")).Count() > 0 ? "true" : "false";
            ViewData["InSysAdminRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("system")).Count() > 0 ? "true" : "false";
            ViewData["InReadRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("read")).Count() > 0 ? "true" : "false";
            ViewData["InStandardRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("standard")).Count() > 0 ? "true" : "false";
            ViewData["InMagistratesReadRole"] = AccessGroupsModel.Where(r => r.AccessGroup.ToLower().Contains("magistrate")).Count() > 0 ? "true" : "false";

            if ((ViewData["InSysAdminRole"] != "true") && (ViewData["InReadRole"] != "true") && (ViewData["InMagistratesReadRole"] != "true") && (ViewData["InStandardRole"] != "true") && (ViewData["InOwnerRole"] != "true"))
            {
                return RedirectToAction("Unauthorised", "Access");
            }

            if (currentUser != null)
                ViewData["UserName"] = currentUser.UserName;
            else
            { ViewData["UserName"] = User.Identity.Name; }

            DayNote model = new DayNote();
            
            model.AvailableDiaries = db.tblDiary.ToList(); //Get a List of diaries
            model.DefaultDiaries = db.tblDiary.Where(r => r.D_DiaryName == "All").ToList();  // Get Default Values for diary
            model.DN_Start_Date = DateTime.Now;
            model.DN_End_Date = DateTime.Now;
            model.DN_BackColor = "White";
            model.DN_TextColor = "Black";

            // pass the view model to the view
            return View(model);
            
        }

        // POST: DayNote/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]

Diaries/Views/DayNote/Create.cshtml
@model Diaries.Models.DayNote

@{
    ViewBag.Title = "Create Day Note";
}


<h3>Day Note</h3>
<p></p>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.DN_ID)

    <p style="font-size:inherit;color:red" >@ViewData["ErrorMessage"]</p>
    
    <table border="0">
        <tr>
            <td class="auto-style16">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "Index", "DayNote", new { @class = "btn btn-danger" })
            </td>
        </tr>
    </table>

    <p></p>


    <table border="1" cellspacing="0" cellpadding="10">
        <tr>
            <td>
                <table border="0" style="font-family: Arial; float: left; font-size: 9pt; background-color: whitesmoke; width: auto; height: 100%; ">
                    <tr style="background-color: #46568c; color: white; "><th align="center"><b>Day Notes</b></th></tr>
                    <tr>
                        <td class="auto-style12">

                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: whitesmoke; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Start Date:
                                    </td>
                                    <td align="left">
                                        <input type="text" class="datepickeryear" data-val="true" data-val-length="The start date must be a date." data-val-length-max="10" data-val-required="The start date must be entered." id="DN_Start_Date" name="DN_Start_Date" value=@Model.DN_Start_Date.ToString("dd-MM-yyyy") style="font-size:12px; padding-top:5px;" />
                                        @Html.ValidationMessageFor(model => model.DN_Start_Date)
                                    </td>
                                </tr>

                            </table>

                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: ThreeDLightShadow; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        End Date:
                                    </td>
                                    <td align="left">
                                        <input type="text" class="datepickeryear" data-val="true" data-val-length="The end date must be a date." data-val-length-max="10" data-val-required="The end date must be entered." id="DN_End_Date" name="DN_End_Date" value=@Model.DN_End_Date.ToString("dd-MM-yyyy") style="font-size:12px; padding-top:5px;" />
                                        @Html.ValidationMessageFor(model => model.DN_End_Date)
                                    </td>
                                </tr>

                            </table>


                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: whitesmoke; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Apply To:
                                    </td>
                                    <td align="left">
                                        @*<p>
                                            <select title="Basic example" class="multiselect" multiple="multiple" name="SubmittedDiaries" id="SubmittedDiaries" size="5"></select>*@

                                        @Html.DropDownList("SubmittedDiaries", new MultiSelectList(Model.AvailableDiaries, "D_id", "D_DiaryName",
                                                    Model.DefaultDiaries.Select(m => m.D_id)),
                                                    new { multiple = "multiple", @class = "multiselect", @style = "width:100px" })
                                        @*</p>*@
                                    </td>
                                </tr>

                            </table>

                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: ThreeDLightShadow; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Note:
                                    </td>
                                    <td align="left">
                                        @Html.EditorFor(model => model.DN_Note)
                                        @Html.ValidationMessageFor(model => model.DN_Note)
                                    </td>
                                </tr>

                            </table>

                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: ThreeDLightShadow; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Active:
                                    </td>
                                    <td align="left">
                                        @*@Html.EditorFor(model => model.IsActive)*@
                                        <input type="checkbox" name="IsActive" id="IsActive" value="true" checked="checked"/>
                                        @Html.ValidationMessageFor(model => model.IsActive)
                                    </td>
                                </tr>

                            </table>

                            


                        </td>

                    </tr>

                </table>

                <table border="0" style="font-family: Arial; float: right; font-size: 9pt; background-color: whitesmoke; width: auto; height: 100%; ">
                    <tr style="background-color: #46568c; color: white; "><th align="center"><b>Colours</b></th></tr>
                    <tr>
                        <td class="auto-style12">
                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: whitesmoke; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Background Colour:
                                    </td>
                                    <td align="left" class="input-group color">
                                        <span class="input-group-addon"><i></i></span>

                                        @Html.ColorPickAreaFor(Model.DN_BackColor, Model.DN_BackColor, "DN_BackColor")
                                        @Html.ValidationMessageFor(model => model.DN_BackColor)

                                        @*<input type="text" name=model. value="" class="form-control" />*@
                                    </td>
                                </tr>

                            </table>
                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: whitesmoke; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Text Colour:
                                    </td>
                                    <td align="left" class="input-group color">
                                        <span class="input-group-addon"><i></i></span>
                                        @Html.ColorPickAreaFor(Model.DN_TextColor, Model.DN_TextColor, "DN_TextColor")
                                        @Html.ValidationMessageFor(model => model.DN_TextColor)
                                    </td>
                                </tr>

                            </table>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

}



Diaries/Views/DayNote/Delete.cshtml
@model Diaries.Models.DayNote

@{
    ViewBag.Title = "Delete Day Note";
}


<h3>Delete Day Note</h3>

<h4>Please confirm delete?</h4>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.DN_ID)
    @Html.HiddenFor(model => model.CreatedBy)
    @Html.HiddenFor(model => model.CreatedOn)
    @Html.HiddenFor(model => model.Deleted)

    <table border="0">
        <tr>
            <td class="auto-style16">
                <input type="submit" value="Delete" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "Index", "DayNote", new { @class = "btn btn-danger" })
            </td>
        </tr>
    </table>

    <p></p>


    <table border="1" cellspacing="0" cellpadding="10">
        <tr>
            <td>
                <table border="0" style="font-family: Arial; float: left; font-size: 9pt; background-color: whitesmoke; width: auto; height: 100%; ">
                    <tr style="background-color: #46568c; color: white; "><th align="center"><b>Day Notes</b></th></tr>
                    <tr>
                        <td class="auto-style12">

                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: whitesmoke; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Start Date:
                                    </td>
                                    <td align="left">
                                        <input type="datetime" readonly="readonly" id="DN_Start_Date" name="DN_Start_Date" value=@Model.DN_Start_Date.ToString("dd-MM-yyyy") style="width:100%; height:100%; font-size:12px; padding-top:5px;" />
                                    </td>
                                </tr>

                            </table>

                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: ThreeDLightShadow; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        End Date:
                                    </td>
                                    <td align="left">
                                        <input type="datetime" readonly="readonly" id="DN_End_Date" name="DN_End_Date" value=@Model.DN_End_Date.ToString("dd-MM-yyyy") style="width:100%; height:100%; font-size:12px; padding-top:5px;" />
                                    </td>
                                </tr>

                            </table>


                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: whitesmoke; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Apply To:
                                    </td>
                                    <td align="left">

                                        @Html.DropDownList("SubmittedDiaries", new MultiSelectList(Model.AvailableDiaries, "D_id", "D_DiaryName",
                                                    Model.DefaultEditableDiaries.Select(m => m.D_id)),
                                                    new { multiple = "multiple", @class = "multiselect", @style = "width:100px" })
                                    </td>
                                </tr>

                            </table>

                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: ThreeDLightShadow; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Note:
                                    </td>
                                    <td align="left">
                                        @Html.DisplayFor(model => model.DN_Note)
                                    </td>
                                </tr>

                            </table>

                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: whitesmoke; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Active:
                                    </td>
                                    <td align="left">
                                        @if (Model.IsActive == true)
                                        {
                                            <input type="checkbox" disabled="disabled" readonly="readonly" name="IsActive" id="IsActive" value=true checked="checked" />
                                        }
                                        else
                                        {
                                            <input type="checkbox" disabled="disabled" readonly="readonly" name="IsActive" id="IsActive" value=false />
                                        }
                                    </td>
                                </tr>

                            </table>




                        </td>

                    </tr>

                </table>

                <table border="0" style="font-family: Arial; float: right; font-size: 9pt; background-color: whitesmoke; width: auto; height: 100%; ">
                    <tr style="background-color: #46568c; color: white; "><th align="center"><b>Colours</b></th></tr>
                    <tr>
                        <td class="auto-style12">
                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: whitesmoke; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Background Colour:
                                    </td>
                                    <td align="left" class="input-group color">
                                        <span class="input-group-addon"><i></i></span>
                                        @Html.ColorPickAreaReadOnlyFor(Model.DN_BackColor, Model.DN_BackColor, "DN_BackColor")
                                    </td>
                                </tr>

                            </table>
                            <table border="0" style="font-family: Arial; font-size: 9pt; width: 100%; background-color: ThreeDLightShadow; float: left" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td align="left" nowrap class="auto-style5" width="auto">
                                        Text Colour:
                                    </td>
                                    <td align="left" class="input-group color">
                                        <span class="input-group-addon"><i></i></span>
                                        @Html.ColorPickAreaReadOnlyFor(Model.DN_TextColor, Model.DN_TextColor, "DN_TextColor")
                                    </td>
                                </tr>

                            </table>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>


    <div>
    @section DocumentLog
{
        <table border="1" cellspacing="0" cellpadding="4" style="font-family: Arial; font-size: 10pt; width: 100%; background-color: threedlightshadow;">
            <tr>
                <td align="left" nowrap class="auto-style14">
                    Record modified by @Model.CreatedBy on @Model.CreatedOn.ToString("dd-MM-yyyy")
                </td>
            </tr>
        </table>

        <table border="1" cellspacing="0" cellpadding="4" style="font-family: Arial; font-size: 10pt; width: 100%; background-color: threedlightshadow;">
            <tr>
                <td align="left" nowrap class="auto-style14">
                    Record created by @Model.ModifiedBy on @Model.ModifiedOn.ToString("dd-MM-yyyy")
                </td>
            </tr>
        </table>
    }
</div>
        
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

}



